service: ton-challenge
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-2
  memorySize: 512

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  api:
    handler: app/handler.handler
    events:
      - httpApi: '*'