service: ton-challenge
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-offline


functions:
  api:
    handler: app/handler.handler
    events:
      - httpApi: '*'
